#!/bin/sh

set -e

ICL_PRODUCT_LOCATION="${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}"
ICL_PRODUCT_BINARY="${TARGET_BUILD_DIR}/${EXECUTABLE_PATH}"

# Core Media
cd "${PROJECT_DIR}/Extensions/Core Media/"

xcodebuild -target "Core Media" \
 -configuration "${ICL_EXTENSION_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 ICL_PRODUCT_LOCATION="${ICL_PRODUCT_LOCATION}" \
 ICL_PRODUCT_BINARY="${ICL_PRODUCT_BINARY}"

exit 0;
