#!/usr/bin/php
<?php
	
	function randomString()
	{
		$characters = '0123456789abcdefghijklmnopqrstuvwxyz';
		
		$charactersLength = (strlen($characters) - 1);
		
		$randomString = '';
		
		$randomString .= $characters[mt_rand(0, $charactersLength)];
		$randomString .= $characters[mt_rand(0, $charactersLength)];
		$randomString .= $characters[mt_rand(0, $charactersLength)];
		$randomString .= "-";
		$randomString .= $characters[mt_rand(0, $charactersLength)];
		$randomString .= $characters[mt_rand(0, $charactersLength)];
		
		return $randomString;
	}
	
	for ($i = 0; $i < 10; $i++) {
		echo randomString()."\n";
	}
	
	exit(0);
