#!/bin/sh

set -e

TEXTUAL_PRODUCT_LOCATION="${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}"
TEXTUAL_PRODUCT_BINARY="${TARGET_BUILD_DIR}/${EXECUTABLE_PATH}"

cd "${TEXTUAL_WORKSPACE_DIR}/Sources/Plugins/Brag Spam"
xcodebuild -target "Brag Spam Extension" \
 -configuration "${TEXTUAL_EXTENSION_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 TEXTUAL_PRODUCT_BINARY="${TEXTUAL_PRODUCT_BINARY}"

cd "${TEXTUAL_WORKSPACE_DIR}/Sources/Plugins/Chat Filter"
xcodebuild -target "Chat Filter Extension" \
 -configuration "${TEXTUAL_EXTENSION_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 TEXTUAL_PRODUCT_BINARY="${TEXTUAL_PRODUCT_BINARY}"

cd "${TEXTUAL_WORKSPACE_DIR}/Sources/Plugins/Smiley Converter"
xcodebuild -target "Smiley Converter Extension" \
 -configuration "${TEXTUAL_EXTENSION_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 TEXTUAL_PRODUCT_BINARY="${TEXTUAL_PRODUCT_BINARY}"

cd "${TEXTUAL_WORKSPACE_DIR}/Sources/Plugins/Spammer Paradise"
xcodebuild -target "Spammer Paradise Extension" \
 -configuration "${TEXTUAL_EXTENSION_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 TEXTUAL_PRODUCT_BINARY="${TEXTUAL_PRODUCT_BINARY}"

cd "${TEXTUAL_WORKSPACE_DIR}/Sources/Plugins/System Profiler"
xcodebuild -target "System Profiler Extension" \
 -configuration "${TEXTUAL_EXTENSION_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 TEXTUAL_PRODUCT_BINARY="${TEXTUAL_PRODUCT_BINARY}"

cd "${TEXTUAL_WORKSPACE_DIR}/Sources/Plugins/ZNC Additions"
xcodebuild -target "ZNC Additions Extension" \
 -configuration "${TEXTUAL_EXTENSION_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 TEXTUAL_PRODUCT_BINARY="${TEXTUAL_PRODUCT_BINARY}"

exit 0;
