#!/bin/sh

set -e

TEXTUAL_PRODUCT_LOCATION="${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME}"
TEXTUAL_PRODUCT_BINARY="${TARGET_BUILD_DIR}/${EXECUTABLE_PATH}"

# Historic Log File Manager
cd "${TEXTUAL_WORKSPACE_DIR}/XPC Services/Historic Log File Manager/"

xcodebuild -target "Historic Log File Manager" \
 -configuration "${TEXTUAL_XPC_SERVICE_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 TEXTUAL_PRODUCT_BINARY="${TEXTUAL_PRODUCT_BINARY}"

cd "${TEXTUAL_WORKSPACE_DIR}/XPC Services/Inline Content Loader/"

xcodebuild -target "Inline Content Loader" \
 -configuration "${TEXTUAL_XPC_SERVICE_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 TEXTUAL_PRODUCT_BINARY="${TEXTUAL_PRODUCT_BINARY}"

cd "${TEXTUAL_WORKSPACE_DIR}/XPC Services/IRC Remote Connection Manager/"

xcodebuild -target "IRC Remote Connection Manager" \
 -configuration "${TEXTUAL_XPC_SERVICE_BUILD_SCHEME}" \
 CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY}" \
 DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
 PROVISIONING_PROFILE_SPECIFIER="" \
 TEXTUAL_WORKSPACE_DIR="${TEXTUAL_WORKSPACE_DIR}" \
 TEXTUAL_PRODUCT_LOCATION="${TEXTUAL_PRODUCT_LOCATION}" \
 TEXTUAL_PRODUCT_BINARY="${TEXTUAL_PRODUCT_BINARY}"

exit 0;
