#!/bin/bash

USER_BUNDLE_PATH="$HOME/Library/Group Containers/8482Q6EPL6.com.codeux.irc.textual/Library/Application Support/Textual/Extensions/"

ZIPPED_BUNDLES="/Library/Caches/com.codeux.irc.textual5/._private-455CE157-E3B7-43D0-8540-F2261A3C446A/
/Library/Caches/com.codeux.irc.textual5/._private-35769194-123E-41A6-AE37-BD20C85F21F9/
/Library/Caches/com.codeux.irc.textual5/._private-73146A9A-04B9-41A1-8A3F-96277831DCE9/
/Library/Caches/com.codeux.irc.textual5/._private-0CDFC530-379B-4E99-8FC2-8BAF3C260667"

if [ ! -f "${USER_BUNDLE_PATH}" ]; then
	mkdir -p "${USER_BUNDLE_PATH}"
fi 

for ZIPPED_PATH in $ZIPPED_BUNDLES; do	
	cd "${ZIPPED_PATH}"

	ZIPPED_BUNDLES=`find . -name "*.tar.gz"`
	
	for BUNDLE in $ZIPPED_BUNDLES; do	
		BUNDLENAME="${BUNDLE%.*}"
		BUNDLENAME="${BUNDLENAME%.*}"
		BUNDLENAME=$(basename $BUNDLENAME)
		
		DESTINATION="${USER_BUNDLE_PATH}${BUNDLENAME}.bundle"
	
		if [ -f "${DESTINATION}" ]; then
			rm -rf "${DESTINATION}"
		fi

		gunzip -c "${BUNDLE}" | tar xopf -
		
		cp -R "./${BUNDLENAME}.bundle" "${DESTINATION}"
	done

	rm -Rf “${ZIPPED_PATH}”
done

exit
