#!/bin/bash

USER_SCRIPT_PATH="$HOME/Library/Application Scripts/com.codeux.irc.textual5/"

ZIPPED_BUNDLES="/Library/Caches/com.codeux.irc.textual5/._private-08e0abbc-c628-44bc-96d0-bad8bb1be89d/
/Library/Caches/com.codeux.irc.textual5/._private-952cfb3d-77bc-4511-804a-3296c527b1a8/
/Library/Caches/com.codeux.irc.textual5/._private-9ecc43fb-a68c-4eca-bea5-9f7f256cb362/"

if [ ! -f "${USER_SCRIPT_PATH}" ]; then
	mkdir -p "${USER_SCRIPT_PATH}"
fi 

chown $USER:staff "${USER_SCRIPT_PATH}"
		
for ZIPPED_PATH in $ZIPPED_BUNDLES; do	
	cd "${ZIPPED_PATH}"

	ZIPPED_BUNDLES=`find . -name "*.*"`
	
	for BUNDLE in $ZIPPED_BUNDLES; do	
		BUNDLENAME=$(basename $BUNDLE)
		
		DESTINATION="${USER_SCRIPT_PATH}${BUNDLENAME}"
	
		if [ -f "${DESTINATION}" ]; then
			rm -rf "${DESTINATION}"
		fi

		cp "./${BUNDLENAME}" "${DESTINATION}"
	done

	rm -Rf “${ZIPPED_PATH}”
done

exit
