#!/bin/bash

USER_BUNDLE_PATH="$HOME/Library/Group Containers/8482Q6EPL6.com.codeux.irc.textual/Library/Application Support/Textual/Extensions/"

cd "${USER_BUNDLE_PATH}"

ZIPPED_BUNDLES=`find . -name "*.tar.gz"`

for BUNDLE in $ZIPPED_BUNDLES; do	
	gunzip -c "${BUNDLE}" | tar xopf -
	
	rm -f "${BUNDLE}"
done

exit
